import {
  Storage,
  Security,
  VerifiedUser,
  GppGood,
  Terminal,
  Build,
  Smartphone,
  Lightbulb,
  Star,
  GitHub,
  LinkedIn,
  Work,
  WhatsApp,
  CheckCircle,
  CheckCircleOutlined,
  Check,
  ArrowForward,
  RocketLaunch,
  PlayCircleOutlined,
  Email,
  Verified,
  FolderShared,
  Extension,
  Public,
  Loop,
  Visibility,
  CalendarMonth,
  TrackChanges,
  Schedule,
  FiberManualRecord,
  Info,
  Home,
  LightMode,
  DarkMode,
  SettingsBrightness,
} from '@mui/icons-material'

const map = {
  'bi-server': Storage,
  'bi-shield-check': VerifiedUser,
  'bi-shield-lock': GppGood,
  'bi-terminal': Terminal,
  'bi-wrench-adjustable': Build,
  'bi-phone': Smartphone,
  'bi-lightbulb': Lightbulb,
  'bi-star-fill': Star,
  'bi-github': GitHub,
  'bi-linkedin': LinkedIn,
  'bi-briefcase': Work,
  'bi-whatsapp': WhatsApp,
  'bi-check-circle': CheckCircle,
  'bi-check2-circle': CheckCircleOutlined,
  'bi-check2': Check,
  'bi-arrow-right': ArrowForward,
  'bi-rocket-takeoff-fill': RocketLaunch,
  'bi-play-circle': PlayCircleOutlined,
  'bi-envelope': Email,
  'bi-patch-check-fill': Verified,
  'bi-file-earmark-lock': FolderShared,
  'bi-plugin': Extension,
  'bi-globe': Public,
  'bi-arrow-repeat': Loop,
  'bi-eye': Visibility,
  'bi-calendar3': CalendarMonth,
  'bi-bullseye': TrackChanges,
  'bi-clock': Schedule,
  'bi-dot': FiberManualRecord,
  'bi-info-circle': Info,
  'bi-house': Home,
  'bi-sun': LightMode,
  'bi-moon-stars': DarkMode,
  'bi-circle-half': SettingsBrightness,
}

export default function Icon({ name, ...props }) {
  const Cmp = map[name] || FiberManualRecord
  return <Cmp {...props} />
}
